/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_chauhandevs_hacked_fepo_mitm_attacker_sniffing_spoofing_ArpPoisoner */

#ifndef _Included_net_chauhandevs_hacked_fepo_mitm_attacker_sniffing_spoofing_ArpPoisoner
#define _Included_net_chauhandevs_hacked_fepo_mitm_attacker_sniffing_spoofing_ArpPoisoner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_chauhandevs_hacked_fepo_mitm_attacker_sniffing_spoofing_ArpPoisoner
 * Method:    arp_poison
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_net_chauhandevs_hacked_fepo_mitm_1attacker_sniffing_1spoofing_ArpPoisoner_arp_1poison
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
